---
title: "Ex1"
output: html_document
---
#ex1-1
Write a function, compare arithmetic mean and trimmed mean, n1 from normal dist, n2 from t3 dist with average mu. check bias and RMSE.

```{r}
estimators.sim <- function(n1,n2,mu = 0, R = 10 ^4, ...) {
  m1 <- m2 <- rep(NA, R) #assign both to NA vals
  for (i in 1:R) {
        y1 <- rnorm(n1, mean = mu) #normal dist
        y2 <-  rt(n2, df = 3) + mu #t3 dist, what is + mu?
        y <-  c(y1,y2) #total vector
        m1[i] <- mean(y) #aritmetic mean
        m2[i] <- mean(y, ...) #... = trim
  } #for loop!
  out <- list(mean = m1, trimmed.mean = m2, mu = mu, n1 = n1, n2 = n2) #list with names of elements
  class(out) <-  "sim"
  return(out)
}
```


```{r}
summary.sim <- function(res) {
  biasm1 <- mean(res$mean) - res$mu
  biasm2 <- mean(res$trimmed.mean) - res$mu
  RMSEm1 <- sqrt(mean((res$mean - res$mu)^2))
  RMSEm2 <- sqrt(mean((res$trimmed.mean - res$mu)^2))
  out <- matrix(c(biasm1, biasm2,RMSEm1,RMSEm2),2,2)
  colnames(out) <- c("BIAS","RMSE")
  rownames(out) <- c("mean","trimmed mean")
  return(out)
}
```

```{r}
plot.sim <-  function(res){
  boxplot(res$mean, res$trimmed.mean, names = c("mean", "trimmed mean"))
  abline(h = res$mu, col = 2)
}
```

```{r}
res.20.5 <-  estimators.sim(n1 = 20, n2 = 5, mu = 3, trim = 0.2)
summary.sim(res.20.5)
plot.sim(res.20.5)
```

#ex1-2

```{r}
set.seed(223532)
rweib <-function(n, mu = 1, alpha = 1){
  return((-log(runif(n)))^(1/alpha)*mu) }
hist(rweib(n = 100000, mu = 2, alpha =1.5), nclass = 100,freq = FALSE,xlab = 'values', main = '')
curve(dweibull(x,shape = 1.5, scale = 2), add = T, col = 2)


system.time(rweib(n = 100000, mu = 2, alpha = 1.5))
system.time(rweibull(n = 100000, shape = 1.5, scale = 2))



```

#ex 1-3
generate n random variables with values x and probs p
```{r}
rdiscrete <- function(n, x, p) {
  values <- rep(NA,n)
  P <- cumsum(p)
  for (i in 1:n)
  {
    U <- runif(1)
    j <- 1
    while (U > P[j]) {j <-j+1 }
    
    values[i] <- x[j]
  }
return(values)
}

print(rdiscrete(n = 6, x = 1:3, p = c(1/3,1/6,1/2)))
system.time(rdiscrete(n = 100000, x = 1:3, p = c(1/3,1/6,1/2)))

```

```{r}
rdiscrete2 <-  function(n,x,p)
{
  values <- rep(NA,n)
  x <- x[sort.list(p,decreasing = TRUE)]
  p <- sort(p, decreasing = TRUE)
  P <- cumsum(p)
  for (i in 1:n)
  {
    U <- runif(1)
    j <- 1
    while (U > P[j]) { j <- j+1}
    values[i] = x[j]
  }
  values
}
```

```{r}
p <- c(1/3,1/6,1/2)
x <-  1:3
n <- 100000

system.time(r1 <- rdiscrete(n,x,p))
system.time(r2 <- rdiscrete2(n,x,p))
system.time(r3 <- sample(x, n,prob = p,replace = TRUE))
```

```{r}
table(r1)/length(r1)
```

```{r}
p <- c(1/100,1/100,98/100)
x <-  1:3
n <- 100000

system.time(r1 <-  rdiscrete(n,x,p))
```

#ex-4
```{r}
dtriangular <-  function(x) #x is a vector
{
  out <- rep(0,length(x))
  mask <- (x>0)&(x<1)
  out[mask] <- 2-4*abs(x[mask]-0.5)
  out                   
}
curve(dtriangular,-1,2, xlab = 'x',ylab = 'Density')
abline(h = 0,lty='dashed')
segments(0,2,1,2)
b <- optimize(function(x) dtriangular(x)/dbeta(x,2,2)  , c(0,1), maximum = TRUE)$objective
plot(function(x) b*dbeta(x,2,2),0,1,add = TRUE)
print(b)
```

```{r}
triangular.AR <- function(n)
{
  out <- rep(NA,n)
  for (i in 1:n)
  {
    f <- 0
    u <- 1
    while (2*u > f) 
    {
      xstar <- runif(1)
      u <- runif(1)
      f <- 2 - 4*abs(xstar - 0.5) #function
    }
    out[i] <- xstar
  }
  out
}  
  
#faster
triangular.AR_fast <- function(n) 
{
  out <-  NULL
  b <- 2
  while (length(out)<n)
  {
    xstar <- runif(n*b)
    mask <- runif(n*b)*b < dtriangular(xstar)
    out <- c(out,xstar[mask])
  }
  out[1:n]
}

```

#ex5(?)
```{r}
beta.AR <-  function(n,a,b)
{
  out <- rep(NA,n)
  x_max <- (a-1)/(a+b+2)
  b <- (x_max^(a-1))*((1-x_max)^(b-1))
  
  for (i in 1:n){
    f <- 0
    xstar <- 0
    u <- 1
    while (u*b > f)
    {
      xstar <- runif(1) 
      f <- (xstar^(a-1))*((1-xstar)^(b-1))
      u <- runif(1)
    }
    out[i] <- xstar
  }
  out
}
```

#ex6: Box MULLER ALGORITHM

```{r}
rnormal <-  function(m)
{
  n <- ceiling(m/2)
  U1 <- runif(n)
  U2 <- runif(n)
  theta <-  2*pi*U1
  R <- sqrt(-2*log(U2))
  X <- R*cos(theta)
  Y <- R*sin(theta)
  out <-  c(X,Y)
  out[1:n]
}  
```

```{r}
#accept - reject: 2D
rnormal.AR <-  function(n){
  m <- ceiling(n/2)
  out <-  rep(NA,2*m)
  for (i in 1:m){
    S <- 2
    while (S> 1){
      U <- runif(2)
      V <- 2*U -1 
      S <-  sum(V^2)
    }
    Z1 <-  V[1]*(-2/S*log(S))^0.5
    Z2 <-  V[2]*(-2/S*log(S))^0.5
    out[c(i,i+m)] <-  c(Z1,Z2)
  }
  out[1:n]
}  

```

#ex7 relation of uniforms

```{r}
rt3 <-  function(n){
  out <-  rep(NA,n)
  for (i in 1:n){
    fsq <-  0 
    v <-1
    while (v^2 > fsq){
      u <-  runif(1)
      v <-  runif(1, -sqrt(3/2),sqrt(3/2))
      fsq <-  3*u -3*u^2
    }
  out[i] <- v/u  
  }
out  
}
```

```{r}
dt3p <-  function(x) (1+x^2/3)^-2

a <- sqrt(-nlminb(5,function(x) -dt3p(x))$objective)
print(a)
```

```{r}
bm <- -sqrt(-nlminb(-5,function(x) -x^2*dt3p(x))$objective)
print(bm)

bp <- sqrt(-nlminb(5,function(x) -x^2*dt3p(x))$objective)
print(bp)
```


---Note that the `echo = FALSE` parameter IS added to the code chunk to prevent printing of the R code that generated the plot.
